### ISSUE TITLE
运行一键式脚本报错：The Compose file './pull_build.yml' is invalid

### ISSUE THREAD

**Issue by XYZliang** [barats/ohUrlShortener#15]
`root@ubuntu:/docker# ./one_step_start.sh
ERROR: The Compose file './pull_build.yml' is invalid because:
networks.ohurlshortener value Additional properties are not allowed ('name' was unexpect
ed)
services.ohurlshortener-admin.depends_on contains an invalid type, it should be an array
services.ohurlshortener-portal.depends_on contains an invalid type, it should be an arra
y`

**Comment by barats** [comment]
> `root@ubuntu:/docker# ./one_step_start.sh ERROR: The Compose file './pull_build.yml' is invalid because: networks.ohurlshortener value Additional properties are not allowed ('name' was unexpect ed) services.ohurlshortener-admin.depends_on contains an invalid type, it should be an array services.ohurlshortener-portal.depends_on contains an invalid type, it should be an arra y`

如果是 Ubuntu 环境下，请把 `pull_build.yml` 文件最底部的 `network` 配置里的 `name: "network_ohurlshortener"` 去掉

亦即，关于网络的相关配置变成：

```
networks:
  ohurlshortener:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
```
